In [36]:
import matplotlib.pyplot as plt
import numpy as np
import math

In [37]:
# Loading CSV:

def loadCSV(filename):
    data = np.loadtxt(filename, delimiter=',', skiprows=1, unpack=False)
    xarray = data[...,0] # Need to get this on a matrix-form!
    numOfColumns = data.shape[1]
    Y = data[...,(numOfColumns-1)]
    return data, xarray, Y
    
dataTrain, xarrayTrain, YTrain = loadCSV('cl_train_1.csv')
dataTest, xarrayTest, YTest = loadCSV('cl_test_1.csv')

In [39]:
# Place 1 in position 0 in each x-array in the matrix X:

def addOnes(data,xArrayWithoutOnes):
    X = np.ones((len(xArrayWithoutOnes), (data.shape[1])))
    place = 0
    
    #1D
    if data.shape[1] == 2:
        for obs in xArrayWithoutOnes:
            # Put one obs in each place in X
            X[place,1] = obs
            place+=1
    #2D
    if data.shape[1] == 3:
        place = 0
        for obs in data:
            # Put one obs in each place in X
            X[place,1]= obs[1]
            X[place,2] = obs[2]
            place+=1
    return X

XTrain = addOnes(dataTrain,xarrayTrain)
XTest = addOnes(dataTest, xarrayTest)

In [ ]:
# Logistic Regression with Gradient descent. Defining functions:

# z = h(x)
def linearSignal(w, x):
    return (w.T).dot(x)

# Sigma, the sigmoid function. Returns a number between 0 and 1. 
def logistic(z):
    return ( 1 / (1 + math.exp(-z)))
    
# Returns a probability that the datapoint (1,x1,x2) is in y.
def prob(w,x,y):
    z = linearSignal(w,x)
    probability = (logistic(z)**y)*(1 - logistic(z))**(1-y)
    return probability

# Calculating the cross-entropy error on the training and the test-set:
def CEE(w):
    logistic()

    

In [85]:
# Gradient descent:

def gradientDescent(X,Y,LR,weights,iterations):
    it = 0
    while it <= iterations:
        
        place = 0
        summ = 0
        
        for x in X:

            summ = summ + (logistic(linearSignal(weights,x)) - Y[place])*x
            place+=1
            
        weights = weights - (LR*summ)
        it+=1
    return weights

# Setting the initial weights in the range -0.5 to 0.5:
initWeights = np.array([0.2, 0.2,0.2])

# learning rate in the range -0.5 to 0.5:
trained_Weights1 = gradientDescent(XTrain,YTrain, 0.5,initWeights, 10)
trained_Weights2 = gradientDescent(XTrain,YTrain, 0.5,initWeights, 100)
trained_Weights3 = gradientDescent(XTrain,YTrain, 0.5,initWeights, 1000)
trained_Weights4 = gradientDescent(XTrain,YTrain, 0.5,initWeights, 5000)
trained_Weights5 = gradientDescent(XTrain,YTrain, 0.5,initWeights, 8000)
trained_Weights6 = gradientDescent(XTrain,YTrain, 0.5,initWeights, 10000)
trained_Weights7 = gradientDescent(XTrain,YTrain, 0.5,initWeights, 12000)


print(trained_Weights1)
print(trained_Weights2)
print(trained_Weights3)
print(trained_Weights4)
print(trained_Weights5)
print(trained_Weights6)
print(trained_Weights7)

# Looks like it is converging!

[-6.16536558  2.45810008 21.1851329 ]
[-7.98095304  1.52235986 21.18583049]
[-9.80644981  0.70143448 21.25066209]
[-10.79382799   0.41640576  22.00513745]
[-11.05452221   0.39757645  22.50092381]
[-11.19171058   0.39086856  22.77667666]
[-11.31135966   0.38568705  23.01944366]
