In [1]:
import numpy as np
import pandas as pd
from random import *
import random
import decimal


# https://www.youtube.com/watch?v=QJoa0JYaX1I 16:20

In [2]:
df = pd.read_csv("xOR_problem.csv").loc[:,'0':'0.2']
X_train = df.loc[:,'0':'0.1']
Y_train = df.loc[:,'0.2']
print(df)
print(" ")


   0  0.1  0.2
0  1    1    0
1  0    1    1
2  1    0    1
3  0    0    0
 


In [ ]:
## Need to generalize it for n layers! it is generalized for n nodes in the 3 layers.
class nn:
    # input_nodes = 0
    # hidden_nodes = 0
    # output_nodes = 0
    
    def __init__(self, input_nodes, hidden_nodes, output_nodes):
        self.input_nodes = input_nodes # The number of features!
        self.hidden_nodes = hidden_nodes
        self.output_nodes = output_nodes

        self.weights_ih = np.random.randn(self.hidden_nodes,self.input_nodes )#2x2
        self.weights_ho = np.random.randn(self.output_nodes, self.hidden_nodes)#1x2
        self.bias_h = np.zeros([self.hidden_nodes, 1])#2x1
        self.bias_o = np.zeros([self.output_nodes, 1])#1x1
        self.learning_rate = 0.1

    def sigmoid(self,x):
        res = 1 / (1 + np.exp(-x))
        return res
    
    def feedforward(self, input_sample):
        # Generating the hidden outputs: input_sample: 1x2                input_sample_T = np.asmatrix(input_sample).T
        input_sample_T = np.asmatrix(input_sample).T

        hidden = np.matrix(np.dot(self.weights_ih, input_sample_T))
        hidden = np.add(hidden,self.bias_h)
        sig = lambda t: self.sigmoid(t)
        hidden = sig(hidden)
        
        # Now, generate the output for the output layer:
        outputs = np.matrix(np.dot(self.weights_ho, hidden ))
        outputs = np.add(outputs,self.bias_o)
        sig = lambda t: self.sigmoid(t)
        outputs = sig(outputs)
        output_outputs = np.asmatrix(outputs)

        return hidden, output_outputs
    
    def train(self, input_sample, targets):
        targets = np.asmatrix(targets).T
        
        hidden, outputs =  self.feedforward(input_sample)
    
        # Calculate the errors from the output layer:
        # ERROR = Targets - ypred
        output_errors = np.subtract(targets,outputs)
    
        # Calculate gradient
        # gradient = outputs*(1 - outputs)
        desig = lambda t: self.desigmoid(t)
        gradients = desig(np.asmatrix(outputs))
        gradients = np.multiply(gradients, output_errors)
        gradients = np.multiply(gradients, self.learning_rate)
        
        # Calculate deltas
        hidden_T = hidden.T
        weight_deltas_ho = np.dot(gradients, hidden_T)
        
        # Adjust the weights by the deltas
        self.weights_ho = np.add(self.weights_ho,weight_deltas_ho)
 
        # Adjust the bias by it's deltas:
        self.bias_h = np.add(self.bias_o, gradients)        
 
        # Calculate the error from the hidden node:
        hidden_errors = np.dot(self.weights_ho.T,output_errors)
        
        # Calculate the gradient for the hidden layer:
        hidden_gradient = desig(np.asmatrix(hidden))
        hidden_gradient = np.multiply(hidden_gradient, hidden_errors)
        hidden_gradient = np.multiply(hidden_gradient, self.learning_rate)
        
        # Calculate change of weight for input -> hidden (deltas):
        input_sample_T = np.matrix(input_sample).T
        weight_ih_deltas = np.dot(hidden_gradient, input_sample_T.T)
        
        # Update the input -> Hidden weights:
        self.weights_ih = np.add(self.weights_ih, weight_ih_deltas)
        
        # Adjust the bias by it's deltas:
        self.bias_h = np.add(self.bias_h, hidden_gradient)
        

        
    def desigmoid(self, y):
        res = y.T*(1-y)
        return res
    
    def randomize_weight_matrix(self, rows, cols):
        rand_matrix = np.zeros((rows,cols))
        for i in range(rand_matrix.shape[0]):
            for j in range(rand_matrix.shape[1]):
                rand_matrix[i,j] = random.randint(-100, 101)/100
        return rand_matrix

# ********* Main ***********
# The number of nodes in the neural net:
n1 = nn(2,2,1)
matrix_x = [[]] * 4
list_y = []
j=0
for row in df.iterrows():
    index, data = row
    data = data.tolist()
    y_train = [data.pop(2)]
    x_train = data
    matrix_x[j] = x_train
    list_y.append(y_train[0])
    j+=1
print(list_y)
print(matrix_x)
    
def randomize_train(x,y):
    for i in range(50000):
        rand = randint(0, 3)
        print(x[rand],y[rand])
        n1.train(x[rand], y[rand])
        print(i," ",end='')
        
        
randomize_train(matrix_x, list_y)
    





[0, 1, 1, 0]
[[1, 1], [0, 1], [1, 0], [0, 0]]
[1, 0] 1
0  [0, 0] 0
1  [0, 0] 0
2  [0, 1] 1
3  [0, 1] 1
4  [1, 0] 1
5  [1, 1] 0
6  [1, 0] 1
7  [0, 0] 0
8  [1, 0] 1
9  [1, 0] 1
10  [1, 1] 0
11  [0, 0] 0
12  [1, 0] 1
13  [1, 1] 0
14  [1, 1] 0
15  [1, 1] 0
16  [0, 0] 0
17  [0, 0] 0
18  [0, 1] 1
19  [0, 1] 1
20  [0, 1] 1
21  [1, 0] 1
22  [0, 1] 1
23  [0, 0] 0
24  [0, 0] 0
25  [1, 1] 0
26  [1, 0] 1
27  [0, 1] 1
28  [0, 0] 0
29  [0, 1] 1
30  [1, 1] 0
31  [0, 1] 1
32  [1, 0] 1
33  [1, 0] 1
34  [1, 0] 1
35  [1, 0] 1
36  [0, 0] 0
37  [1, 1] 0
38  [0, 0] 0
39  [1, 1] 0
40  [1, 0] 1
41  [1, 0] 1
42  [1, 0] 1
43  [0, 0] 0
44  [0, 0] 0
45  [1, 1] 0
46  [0, 0] 0
47  [1, 0] 1
48  [0, 0] 0
49  [0, 1] 1
50  [1, 1] 0
51  [0, 0] 0
52  [0, 1] 1
53  [1, 0] 1
54  [1, 0] 1
55  [1, 0] 1
56  [0, 1] 1
57  [0, 0] 0
58  [0, 0] 0
59  [0, 1] 1
60  [0, 1] 1
61  [1, 0] 1
62  [0, 1] 1
63  [0, 0] 0
64  [1, 1] 0
65  [1, 0] 1
66  [1, 0] 1
67  [0, 1] 1
68  [1, 0] 1
69  [0, 0] 0
70  [0, 1] 1
71  [1, 0] 1
72  [1, 1] 0
73  [1

610  [1, 1] 0
611  [0, 1] 1
612  [0, 0] 0
613  [0, 1] 1
614  [0, 1] 1
615  [1, 0] 1
616  [0, 0] 0
617  [0, 0] 0
618  [1, 0] 1
619  [0, 1] 1
620  [0, 1] 1
621  [0, 0] 0
622  [1, 1] 0
623  [1, 0] 1
624  [1, 1] 0
625  [1, 0] 1
626  [1, 0] 1
627  [0, 1] 1
628  [0, 0] 0
629  [0, 0] 0
630  [1, 1] 0
631  [1, 1] 0
632  [1, 0] 1
633  [1, 1] 0
634  [1, 0] 1
635  [1, 0] 1
636  [1, 1] 0
637  [1, 0] 1
638  [1, 1] 0
639  [1, 1] 0
640  [1, 1] 0
641  [0, 0] 0
642  [0, 0] 0
643  [1, 0] 1
644  [1, 0] 1
645  [0, 1] 1
646  [0, 0] 0
647  [0, 0] 0
648  [0, 0] 0
649  [0, 0] 0
650  [1, 0] 1
651  [0, 1] 1
652  [1, 1] 0
653  [0, 0] 0
654  [1, 0] 1
655  [1, 0] 1
656  [1, 1] 0
657  [1, 1] 0
658  [0, 1] 1
659  [1, 1] 0
660  [0, 1] 1
661  [1, 0] 1
662  [0, 1] 1
663  [0, 1] 1
664  [1, 0] 1
665  [0, 1] 1
666  [0, 0] 0
667  [1, 0] 1
668  [1, 0] 1
669  [1, 0] 1
670  [0, 0] 0
671  [1, 1] 0
672  [1, 1] 0
673  [1, 1] 0
674  [0, 1] 1
675  [0, 1] 1
676  [0, 1] 1
677  [1, 1] 0
678  [1, 1] 0
679  [0, 1] 1
680  [1, 1] 0
681  [

1209  [0, 0] 0
1210  [0, 0] 0
1211  [1, 0] 1
1212  [0, 1] 1
1213  [0, 1] 1
1214  [1, 0] 1
1215  [0, 1] 1
1216  [0, 1] 1
1217  [0, 1] 1
1218  [0, 1] 1
1219  [1, 0] 1
1220  [0, 0] 0
1221  [1, 0] 1
1222  [0, 0] 0
1223  [1, 0] 1
1224  [0, 0] 0
1225  [0, 0] 0
1226  [0, 1] 1
1227  [0, 1] 1
1228  [0, 1] 1
1229  [1, 1] 0
1230  [0, 0] 0
1231  [0, 1] 1
1232  [1, 1] 0
1233  [0, 0] 0
1234  [1, 1] 0
1235  [1, 0] 1
1236  [0, 0] 0
1237  [0, 0] 0
1238  [0, 1] 1
1239  [1, 1] 0
1240  [1, 1] 0
1241  [0, 0] 0
1242  [1, 1] 0
1243  [1, 1] 0
1244  [1, 1] 0
1245  [0, 1] 1
1246  [1, 1] 0
1247  [1, 1] 0
1248  [1, 0] 1
1249  [0, 0] 0
1250  [1, 1] 0
1251  [0, 0] 0
1252  [1, 0] 1
1253  [0, 1] 1
1254  [1, 1] 0
1255  [0, 1] 1
1256  [1, 1] 0
1257  [0, 1] 1
1258  [1, 1] 0
1259  [0, 1] 1
1260  [1, 0] 1
1261  [0, 1] 1
1262  [0, 0] 0
1263  [1, 0] 1
1264  [0, 0] 0
1265  [1, 1] 0
1266  [0, 0] 0
1267  [1, 1] 0
1268  [1, 1] 0
1269  [0, 0] 0
1270  [1, 0] 1
1271  [0, 0] 0
1272  [0, 0] 0
1273  [1, 1] 0
1274  [1, 1] 0
1275  [1, 

1861  [0, 1] 1
1862  [1, 1] 0
1863  [1, 0] 1
1864  [0, 1] 1
1865  [1, 0] 1
1866  [0, 0] 0
1867  [0, 1] 1
1868  [0, 1] 1
1869  [0, 0] 0
1870  [1, 1] 0
1871  [1, 0] 1
1872  [1, 1] 0
1873  [1, 1] 0
1874  [1, 1] 0
1875  [0, 1] 1
1876  [0, 1] 1
1877  [0, 0] 0
1878  [1, 0] 1
1879  [1, 1] 0
1880  [0, 1] 1
1881  [1, 1] 0
1882  [0, 0] 0
1883  [1, 0] 1
1884  [1, 0] 1
1885  [0, 1] 1
1886  [0, 1] 1
1887  [0, 0] 0
1888  [0, 0] 0
1889  [1, 0] 1
1890  [1, 0] 1
1891  [0, 1] 1
1892  [1, 0] 1
1893  [1, 0] 1
1894  [1, 0] 1
1895  [1, 1] 0
1896  [1, 0] 1
1897  [0, 0] 0
1898  [0, 1] 1
1899  [0, 0] 0
1900  [1, 1] 0
1901  [0, 1] 1
1902  [0, 0] 0
1903  [1, 0] 1
1904  [0, 0] 0
1905  [0, 1] 1
1906  [0, 0] 0
1907  [0, 0] 0
1908  [1, 0] 1
1909  [1, 0] 1
1910  [0, 0] 0
1911  [1, 0] 1
1912  [0, 1] 1
1913  [0, 0] 0
1914  [1, 0] 1
1915  [1, 1] 0
1916  [0, 0] 0
1917  [1, 0] 1
1918  [1, 1] 0
1919  [0, 1] 1
1920  [1, 0] 1
1921  [0, 1] 1
1922  [1, 1] 0
1923  [1, 1] 0
1924  [1, 1] 0
1925  [0, 0] 0
1926  [0, 1] 1
1927  [1, 

2561  [0, 1] 1
2562  [0, 1] 1
2563  [1, 0] 1
2564  [1, 1] 0
2565  [0, 1] 1
2566  [0, 1] 1
2567  [1, 0] 1
2568  [1, 0] 1
2569  [1, 1] 0
2570  [1, 1] 0
2571  [0, 0] 0
2572  [0, 1] 1
2573  [0, 1] 1
2574  [1, 1] 0
2575  [1, 0] 1
2576  [0, 1] 1
2577  [0, 1] 1
2578  [1, 1] 0
2579  [0, 0] 0
2580  [1, 0] 1
2581  [0, 1] 1
2582  [0, 1] 1
2583  [1, 0] 1
2584  [1, 1] 0
2585  [1, 0] 1
2586  [1, 1] 0
2587  [0, 1] 1
2588  [0, 1] 1
2589  [1, 1] 0
2590  [1, 1] 0
2591  [1, 0] 1
2592  [0, 0] 0
2593  [0, 1] 1
2594  [0, 1] 1
2595  [0, 1] 1
2596  [1, 0] 1
2597  [0, 0] 0
2598  [1, 1] 0
2599  [0, 1] 1
2600  [0, 0] 0
2601  [0, 1] 1
2602  [0, 0] 0
2603  [0, 1] 1
2604  [0, 0] 0
2605  [1, 1] 0
2606  [1, 1] 0
2607  [0, 0] 0
2608  [0, 0] 0
2609  [1, 0] 1
2610  [0, 1] 1
2611  [0, 0] 0
2612  [0, 1] 1
2613  [1, 0] 1
2614  [0, 1] 1
2615  [1, 1] 0
2616  [0, 1] 1
2617  [1, 1] 0
2618  [1, 0] 1
2619  [0, 1] 1
2620  [0, 0] 0
2621  [0, 0] 0
2622  [1, 1] 0
2623  [1, 1] 0
2624  [0, 0] 0
2625  [1, 1] 0
2626  [0, 0] 0
2627  [0, 

3185  [0, 1] 1
3186  [0, 0] 0
3187  [1, 0] 1
3188  [1, 0] 1
3189  [0, 1] 1
3190  [0, 1] 1
3191  [0, 0] 0
3192  [1, 1] 0
3193  [1, 0] 1
3194  [0, 0] 0
3195  [0, 1] 1
3196  [1, 1] 0
3197  [1, 0] 1
3198  [1, 1] 0
3199  [1, 1] 0
3200  [1, 0] 1
3201  [0, 1] 1
3202  [1, 0] 1
3203  [1, 0] 1
3204  [1, 1] 0
3205  [0, 0] 0
3206  [1, 0] 1
3207  [0, 0] 0
3208  [0, 0] 0
3209  [1, 1] 0
3210  [1, 1] 0
3211  [1, 1] 0
3212  [0, 1] 1
3213  [0, 1] 1
3214  [0, 1] 1
3215  [1, 1] 0
3216  [1, 0] 1
3217  [0, 0] 0
3218  [0, 1] 1
3219  [1, 1] 0
3220  [1, 1] 0
3221  [1, 1] 0
3222  [1, 0] 1
3223  [1, 1] 0
3224  [1, 0] 1
3225  [1, 1] 0
3226  [1, 1] 0
3227  [1, 0] 1
3228  [0, 1] 1
3229  [1, 0] 1
3230  [0, 0] 0
3231  [0, 0] 0
3232  [0, 0] 0
3233  [1, 1] 0
3234  [0, 0] 0
3235  [1, 1] 0
3236  [0, 0] 0
3237  [1, 1] 0
3238  [0, 0] 0
3239  [1, 0] 1
3240  [0, 1] 1
3241  [0, 0] 0
3242  [0, 1] 1
3243  [0, 0] 0
3244  [0, 1] 1
3245  [1, 0] 1
3246  [1, 1] 0
3247  [0, 0] 0
3248  [0, 1] 1
3249  [1, 1] 0
3250  [1, 1] 0
3251  [1, 

4023  [0, 0] 0
4024  [0, 1] 1
4025  [0, 0] 0
4026  [0, 0] 0
4027  [0, 1] 1
4028  [1, 1] 0
4029  [1, 1] 0
4030  [1, 0] 1
4031  [0, 0] 0
4032  [0, 1] 1
4033  [0, 1] 1
4034  [1, 1] 0
4035  [1, 1] 0
4036  [1, 1] 0
4037  [1, 1] 0
4038  [1, 1] 0
4039  [0, 1] 1
4040  [0, 1] 1
4041  [0, 1] 1
4042  [0, 1] 1
4043  [0, 0] 0
4044  [1, 1] 0
4045  [1, 0] 1
4046  [1, 0] 1
4047  [0, 1] 1
4048  [1, 1] 0
4049  [0, 1] 1
4050  [0, 0] 0
4051  [0, 1] 1
4052  [0, 0] 0
4053  [0, 1] 1
4054  [0, 1] 1
4055  [1, 0] 1
4056  [0, 1] 1
4057  [0, 0] 0
4058  [0, 1] 1
4059  [0, 0] 0
4060  [0, 1] 1
4061  [0, 0] 0
4062  [1, 0] 1
4063  [1, 1] 0
4064  [0, 1] 1
4065  [1, 1] 0
4066  [0, 1] 1
4067  [1, 1] 0
4068  [0, 1] 1
4069  [0, 1] 1
4070  [0, 0] 0
4071  [1, 0] 1
4072  [1, 1] 0
4073  [1, 1] 0
4074  [1, 1] 0
4075  [0, 0] 0
4076  [1, 0] 1
4077  [0, 0] 0
4078  [1, 1] 0
4079  [0, 0] 0
4080  [0, 1] 1
4081  [0, 0] 0
4082  [1, 0] 1
4083  [1, 1] 0
4084  [1, 0] 1
4085  [0, 0] 0
4086  [0, 1] 1
4087  [0, 1] 1
4088  [1, 1] 0
4089  [1, 

4900  [1, 0] 1
4901  [1, 1] 0
4902  [0, 0] 0
4903  [1, 1] 0
4904  [1, 0] 1
4905  [0, 1] 1
4906  [1, 1] 0
4907  [1, 0] 1
4908  [0, 1] 1
4909  [0, 1] 1
4910  [0, 1] 1
4911  [0, 1] 1
4912  [0, 0] 0
4913  [1, 1] 0
4914  [1, 1] 0
4915  [0, 0] 0
4916  [0, 1] 1
4917  [0, 0] 0
4918  [1, 0] 1
4919  [1, 1] 0
4920  [0, 1] 1
4921  [1, 0] 1
4922  [0, 0] 0
4923  [0, 0] 0
4924  [1, 1] 0
4925  [0, 0] 0
4926  [0, 1] 1
4927  [0, 1] 1
4928  [0, 1] 1
4929  [1, 1] 0
4930  [0, 0] 0
4931  [1, 0] 1
4932  [1, 0] 1
4933  [1, 1] 0
4934  [1, 0] 1
4935  [0, 0] 0
4936  [1, 1] 0
4937  [0, 0] 0
4938  [0, 1] 1
4939  [1, 0] 1
4940  [1, 1] 0
4941  [0, 0] 0
4942  [0, 1] 1
4943  [0, 1] 1
4944  [1, 0] 1
4945  [0, 0] 0
4946  [0, 0] 0
4947  [0, 1] 1
4948  [0, 0] 0
4949  [0, 0] 0
4950  [0, 1] 1
4951  [0, 1] 1
4952  [0, 0] 0
4953  [1, 0] 1
4954  [1, 0] 1
4955  [1, 0] 1
4956  [0, 1] 1
4957  [0, 1] 1
4958  [0, 0] 0
4959  [1, 0] 1
4960  [0, 0] 0
4961  [1, 0] 1
4962  [1, 0] 1
4963  [1, 1] 0
4964  [1, 1] 0
4965  [1, 1] 0
4966  [1, 

In [50]:
h, o = n1.feedforward([1,1])
print(o)


h, o = n1.feedforward([0,0])
print(o) 

h, o = n1.feedforward([0,1])
print(o) 

h, o = n1.feedforward([1,0])
print(o) 


[[0.63809309]]
[[0.0468546]]
[[0.63751791]]
[[0.63762831]]


In [ ]:
class test: 

In [391]:
def randomize_weight_matrix1(rows, cols):
    rand_matrix = np.zeros((rows,cols))
    for i in range(rand_matrix.shape[0]):
        for j in range(rand_matrix.shape[1]):
            rand_matrix[i,j] = random.randint(-100, 101)/100
    return rand_matrix



a = np.random.rand(2, 3)
print(a)

b = randomize_weight_matrix1(2,3)
print(b)

[[0.95744045 0.86117756 0.00263749]
 [0.29470666 0.35146137 0.90569082]]
[[ 0.32  0.83  0.82]
 [-0.72 -0.39 -0.35]]


In [26]:
print(np.random.randn(3, 2))

[[-0.43897801  0.44907989]
 [-0.6761472   0.49722279]
 [ 1.19449986 -1.91206252]]
