In [39]:
import numpy as np
# https://www.youtube.com/watch?v=QJoa0JYaX1I 16:20

In [45]:
## Need to generalize it for n layers! it is generalized for n nodes in the 3 layers.
class nn:
    input_nodes = 0
    hidden_nodes = 0
    output_nodes = 0
    
    def __init__(self, input_nodes, hidden_nodes, output_nodes):
        self.input_nodes = input_nodes # The number of features!
        self.hidden_nodes = hidden_nodes
        self.output_nodes = output_nodes

        self.weights_ih = np.random.rand(self.hidden_nodes, self.input_nodes)
        self.weights_ho = np.random.rand(self.output_nodes, self.hidden_nodes)
        print(self.weights_ho)

        self.bias_h = np.empty([self.hidden_nodes, 1])
        self.bias_o = np.empty([self.output_nodes, 1])

    def sigmoid(self,x):
        res = 1 / (1 + np.exp(-x))
        return res
    
    def feedforward(self, input_sample):
        
        # Generation the hidde outputs:
        hidden = np.matrix(np.dot(self.weights_ih, input_sample)).T
        hidden = np.add(hidden,self.bias_h)
        print(self.bias_h)

        sig = lambda t: self.sigmoid(t)
        # Generate the output using the activation function:
        output_hidden_layer = sig(hidden)
        print(output_hidden_layer)
        
        
        # Now, generate the output for the output layer!
        output = np.matrix(np.dot(self.weights_ho, output_hidden_layer )).T
        output = np.add(output,self.bias_o)

        sig = lambda t: self.sigmoid(t)
        output_output_layer = sig(output)
        
    
        return output_output_layer

    def backprop():
        # Implement here ....
        print(" ")
    
    def train(X_train, y_train):
        print(" ")
        
        
n1 = nn(2,2,1)
untrained = n1.feedforward([1,0])
print("FeedForward, untrained:", untrained)

# Store the weights in a matrix:

[[0.72819279 0.19025996]]
[[0.72819279]
 [0.19025996]]
[[0.75670386]
 [0.62667879]]
FeedForward, untrained: [[0.7027689]]
