In [24]:
import numpy as np
# https://www.youtube.com/watch?v=QJoa0JYaX1I 16:20

In [67]:
## Need to generalize it for n layers! it is generalized for n nodes in the 3 layers.
class nn:
    input_nodes = 0
    hidden_nodes = 0
    output_nodes = 0
    
    def __init__(self, input_nodes, hidden_nodes, output_nodes):
        self.input_nodes = input_nodes # The number of features!
        self.hidden_nodes = hidden_nodes
        self.output_nodes = output_nodes

        self.weights_ih = np.random.rand(self.hidden_nodes, self.input_nodes)
        self.weights_ho = np.random.rand(self.output_nodes, self.hidden_nodes)
        print(self.weights_ho)

        self.bias_h = np.empty([self.hidden_nodes, 1])
        self.bias_o = np.empty([self.output_nodes, 1])

    def sigmoid(self,x):
        res = 1 / (1 + np.exp(-x))
        return res
    
    def feedforward(self, input_sample):
        
        # Generating the hidden outputs:
        hidden = np.matrix(np.dot(self.weights_ih, input_sample)).T
        hidden = np.add(hidden,self.bias_h)
        print("self.sigmoid(hidden)")
        print(self.sigmoid(hidden))

        sig = lambda t: self.sigmoid(t)
        
        # Generate the output using the activation function:
        output_hidden_layer = sig(hidden)
        
        # Now, generate the output for the output layer!
        output = np.matrix(np.dot(self.weights_ho, output_hidden_layer )).T
        output = np.add(output,self.bias_o)

        sig = lambda t: self.sigmoid(t)
        output_output_layer = sig(output)

        return output_output_layer

    def backprop():
        # Implement here ....
        print(" ")
    
    def train(self, inputs, targets):
        outputs = self.feedforward(inputs)
        outputs = np.asmatrix(outputs)
        output_errors = np.subtract(targets,outputs)
        
        # Calculate the hidden layer errors:
        
        print("shape", self.weights_ih.T.shape)
        print("output_errors", output_errors.shape)
        # hidden_errors = np.dot(self.weights_ih.T,output_errors)
        return outputs, targets, output_errors
        
        
n1 = nn(2,2,2)
x_train = [1,0]
y_train = [1,0]
untrained, targets, output_errors = n1.train(x_train,y_train)

print(" ")
print("untrained")
print(untrained)
print("targets:")
print(targets)
print("error")
print(error)

# Store the weights in a matrix:

[[0.37661347 0.06314402]
 [0.34138444 0.01423211]]
self.sigmoid(hidden)
[[0.76747497]
 [0.60452683]]
shape (2, 2)
output_errors (2, 2)
 
untrained
[[0.58108126 0.56724209]
 [0.58108126 0.56724209]]
targets:
[1, 0]
error
[[0.11964567]]
